In [225]:
import pandas as pd
import numpy as np
import math

In [2]:
import urllib

In [8]:
response = urllib.request.urlopen('https://games.crossfit.com/leaderboard/games/2019?division=1&sort=0')

In [268]:
data_1 = open("/Users/thomasnicholson/Documents/games_data_1_w.txt", 'r')
data_2 = open("/Users/thomasnicholson/Documents/games_data_2_w.txt", 'r')
numRows = 129
numCols  = 15

In [269]:
data_1.seek(0)
data_2.seek(0)
games_data_1 = pd.DataFrame(index=range(numRows),columns=range(numCols))
games_data_1.columns = ['RANK', 'NAME', 'POINTS', 'FIRST_CUT', 'SECOND_CUT', 
                        'RUCK', 'SPRINT_COUPLET', 'MARY', 'SPRINT', 'SPLIT_TRIPLET',
                        'CLEAN', 'SWIM_PADDLE', 'RINGER_1', 'RINGER_2', 'THE_STANDARD']
counter = 0
position = 0
columns_by_line = ['RANK', 'NAME', 'NAME', 'COUNTRY', 'COUNTRY', 'AGE', 'STATS', 'PROFILE', 
                   'POINTS', 'FIRST_CUT', 'SECOND_CUT', 
                   'RUCK', 'SPRINT_COUPLET', 'MARY', 'SPRINT']
for line in data_1:
    line = line.rstrip()
    if 'pts' in line:
        continue
    rank = counter + 1
    rank_num = counter - 1
    rank = str(rank)

    
    if line == rank:
#         print(line)
        counter += 1
        position = 0
    if counter == 0:
        continue
#     print(position)
#     print(line)
#     print('%s %s' % (columns_by_line[position] ,line))
    if columns_by_line[position] in games_data_1.columns:
        col_num = games_data_1.columns.get_loc(columns_by_line[position])
        if pd.isna(games_data_1.iloc[rank_num,col_num]):
            games_data_1.iloc[rank_num,col_num] = line
        else:
            games_data_1.iloc[rank_num,col_num] = '%s %s' %(games_data_1.iloc[rank_num,col_num],line)
    position += 1
    if position == 15:
        position = 0

columns_by_line = ['RANK', 'NAME', 'NAME', 'COUNTRY', 'COUNTRY', 'AGE', 'STATS', 'PROFILE', 
                   'POINTS', 'SPLIT_TRIPLET', 'CLEAN', 'SWIM_PADDLE', 'RINGER_1', 'RINGER_2', 
                   'THE_STANDARD']        
counter = 0
position = 0
for line in data_2:
    line = line.rstrip()
    if 'pts' in line:
        continue
    rank = counter + 1
    rank_num = counter - 1
    rank = str(rank)

    
    if line == rank:
#         print(line)
        counter += 1
        position = 0
    if counter == 0:
        continue
    print(position)
#     print(line)
    print('%s %s' % (columns_by_line[position] ,line))
    if columns_by_line[position] in games_data_1.columns:
        col_num = games_data_1.columns.get_loc(columns_by_line[position])
        if pd.isna(games_data_1.iloc[rank_num,col_num]):
            games_data_1.iloc[rank_num,col_num] = line
    position += 1
    if position == 15:
        position = 0

0
RANK 1
1
NAME TIA-CLAIR
2
NAME TOOMEY
3
COUNTRY Australia
4
COUNTRY Australia
5
AGE Age 25
6
STATS 5'4" | 128 lbs
7
PROFILE View Profile
8
POINTS 1071
9
SPLIT_TRIPLET 1st (14:07.10)
10
CLEAN 1st (265.0 lb)
11
SWIM_PADDLE 1st (25:12.25)
12
RINGER_1 4th (5:44.63)
13
RINGER_2 3rd (3:14.03)
14
THE_STANDARD 1st (8:25.09)
0
RANK 2
1
NAME KRISTIN
2
NAME HOLTE
3
COUNTRY Norway
4
COUNTRY Norway
5
AGE Age 33
6
STATS 5'4" | 130 lbs
7
PROFILE View Profile
8
POINTS 876
9
SPLIT_TRIPLET 5th (16:10.92)
10
CLEAN 5th (225.0 lb)
11
SWIM_PADDLE 6th (30:17.62)
12
RINGER_1 3rd (5:43.70)
13
RINGER_2 7th (3:49.14)
14
THE_STANDARD 4th (9:38.26)
0
RANK 3
1
NAME JAMIE
2
NAME GREENE
3
COUNTRY New Zealand
4
COUNTRY New Zealand
5
AGE Age 28
6
STATS 5'4" | 135 lbs
7
PROFILE View Profile
8
POINTS 851
9
SPLIT_TRIPLET 4th (15:32.03)
10
CLEAN 6th (220.0 lb)
11
SWIM_PADDLE 4th (28:32.16)
12
RINGER_1 6th (5:52.21)
13
RINGER_2 6th (3:35.62)
14
THE_STANDARD 2nd (9:14.71)
0
RANK 4
1
NAME KATR√çN TANJA
2
NAME DAVIDSDOTTIR
3
COUNTRY Iceland
4
COUNTRY Iceland
5
AGE Age 26
6
STATS 5'7" | 150 lbs
7
PROFILE View Profile
8
POINTS 784
9
SPLIT_TRIPLET 3rd (15:10.09)
10
CLEAN 4th (230.0 lb)
11
SWIM_PADDLE 8th (32:36.98)
12
RINGER_1 1st (5:09.87)
13
RINGER_2 1st (2:53.29)
14
THE_STANDARD 9th (10:56.22)
0
RANK 5
1
NAME KARISSA
2
NAME PEARCE
3
COUNTRY United States
4
COUNTRY United States
5
AGE Age 30
6
STATS 5'3" | 139 lbs
7
PROFILE View Profile
8
POINTS 714
9
SPLIT_TRIPLET 2nd (14:34.71)
10
CLEAN 8th (0.0 lb)
11
SWIM_PADDLE 7th (31:34.67)
12
RINGER_1 7th (5:54.13)
13
RINGER_2 10th (CAP+8)
14
THE_STANDARD 5th (9:47.12)
0
RANK 6
1
NAME HALEY
2
NAME ADAMS
3
COUNTRY United States
4
COUNTRY United States
5
AGE Age 18
6
STATS 5'6" | 143 lbs
7
PROFILE View Profile
8
POINTS 711
9
SPLIT_TRIPLET 6th (17:28.35)
10
CLEAN 10th (0.0 lb)
11
SWIM_PADDLE 2nd (28:18.50)
12
RINGER_1 5th (5:45.49)
13
RINGER_2 5th (3:33.52)
14
THE_STANDARD 8th (10:40.00)
0
RANK 7
1
NAME AMANDA
2
NAME BARNHART
3
COUNTRY United States
4
COUNTRY United States
5
AGE Age 27
6
STATS 5'7" | 155 lbs
7
PROFILE View Profile
8
POINTS 706
9
SPLIT_TRIPLET 10th (CAP+17)
10
CLEAN 2nd (260.0 lb)
11
SWIM_PADDLE 5th (28:32.52)
12
RINGER_1 8th (6:00.45)
13
RINGER_2 2nd (3:06.76)
14
THE_STANDARD 6th (10:04.82)
0
RANK 8
1
NAME BETHANY
2
NAME SHADBURNE
3
COUNTRY United States
4
COUNTRY United States
5
AGE Age 25
6
STATS 5'4" | 145 lbs
7
PROFILE View Profile
8
POINTS 659
9
SPLIT_TRIPLET 7th (17:54.87)
10
CLEAN 9th (0.0 lb)
11
SWIM_PADDLE 3rd (28:26.58)
12
RINGER_1 2nd (5:38.21)
13
RINGER_2 9th (3:59.96)
14
THE_STANDARD 10th (10:57.10)
0
RANK DQ
1
NAME ANNA
2
NAME FRAGKOU
3
COUNTRY Greece
4
COUNTRY Greece
5
AGE Age 29
6
STATS 5'3" | 139 lbs
7
PROFILE View Profile
8
POINTS 640
9
SPLIT_TRIPLET 9th (CAP+10)
10
CLEAN 3rd (230.0 lb)
11
SWIM_PADDLE 10th (38:58.31)
12
RINGER_1 9th (6:11.82)
13
RINGER_2 8th (3:59.06)
14
THE_STANDARD 3rd (9:34.27)
0
RANK 9
1
NAME THURIDUR ERLA
2
NAME HELGADOTTIR
3
COUNTRY Iceland
4
COUNTRY Iceland
5
AGE Age 27
6
STATS 5'5" | 130 lbs
7
PROFILE View Profile
8
POINTS 611
9
SPLIT_TRIPLET 8th (19:21.03)
10
CLEAN 7th (215.0 lb)
11
SWIM_PADDLE 9th (32:42.99)
12
RINGER_1 10th (CAP)
13
RINGER_2 4th (3:16.45)
14
THE_STANDARD 7th (10:35.00)
0
RANK 10
1
NAME DANIELLE
2
NAME BRANDON
3
COUNTRY United States
4
COUNTRY United States
5
AGE Age 23
6
STATS 5'7" | 150 lbs
7
PROFILE View Profile
8
POINTS 376
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 11
1
NAME ANNIE
2
NAME THORISDOTTIR
3
COUNTRY Iceland
4
COUNTRY Iceland
5
AGE Age 29
6
STATS 5'7" | 152 lbs
7
PROFILE View Profile
8
POINTS 370
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 12
1
NAME CAROLYNE
2
NAME PREVOST
3
COUNTRY Canada
4
COUNTRY Canada
5
AGE Age 29
6
STATS 5'3" | 144 lbs
7
PROFILE View Profile
8
POINTS 365
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 13
1
NAME ALESSANDRA
2
NAME PICHELLI
3
COUNTRY Italy
4
COUNTRY Italy
5
AGE Age 33
6
STATS 5'6" | 155 lbs
7
PROFILE View Profile
8
POINTS 365
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 14
1
NAME LAURA
2
NAME HORVATH
3
COUNTRY Hungary
4
COUNTRY Hungary
5
AGE Age 22
6
STATS 5'7" | 152 lbs
7
PROFILE View Profile
8
POINTS 356
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 15
1
NAME BROOKE
2
NAME WELLS
3
COUNTRY United States
4
COUNTRY United States
5
AGE Age 24
6
STATS 5'6" | 150 lbs
7
PROFILE View Profile
8
POINTS 351
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 16
1
NAME CAROL-ANN
2
NAME REASON-THIBAULT
3
COUNTRY Canada
4
COUNTRY Canada
5
AGE Age 31
6
STATS 5'5" | 145 lbs
7
PROFILE View Profile
8
POINTS 328
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 17
1
NAME SAMANTHA
2
NAME BRIGGS
3
COUNTRY United Kingdom
4
COUNTRY United Kingdom
5
AGE Age 37
6
STATS 5'7" | 135 lbs
7
PROFILE View Profile
8
POINTS 318
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 18
1
NAME EMILY
2
NAME ROLFE
3
COUNTRY Canada
4
COUNTRY Canada
5
AGE Age 30
6
STATS 5'7" | 150 lbs
7
PROFILE View Profile
8
POINTS 317
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 19
1
NAME RAGNHEI√êUR SARA
2
NAME SIGMUNDSDOTTIR
3
COUNTRY Iceland
4
COUNTRY Iceland
5
AGE Age 26
6
STATS 5'8" | 152 lbs
7
PROFILE View Profile
8
POINTS 294
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 20
1
NAME EMMA
2
NAME MCQUAID
3
COUNTRY Ireland
4
COUNTRY Ireland
5
AGE Age 29
6
STATS 5'5" | 141 lbs
7
PROFILE View Profile
8
POINTS 255
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 21
1
NAME KARIN
2
NAME FREYOV√Å
3
COUNTRY Slovakia
4
COUNTRY Slovakia
5
AGE Age 24
6
STATS 5'7" | 161 lbs
7
PROFILE View Profile
8
POINTS 254
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 22
1
NAME MADELINE
2
NAME STURT
3
COUNTRY Australia
4
COUNTRY Australia
5
AGE Age 22
6
STATS 5'2" | 137 lbs
7
PROFILE View Profile
8
POINTS 244
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 23
1
NAME MEG
2
NAME REARDON
3
COUNTRY United States
4
COUNTRY United States
5
AGE Age 27
6
STATS 5'6" | 150 lbs
7
PROFILE View Profile
8
POINTS 243
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 24
1
NAME FEEROOZEH
2
NAME SAGHAFI
3
COUNTRY United States
4
COUNTRY United States
5
AGE Age 24
6
STATS 5'2" | 127 lbs
7
PROFILE View Profile
8
POINTS 237
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 25
1
NAME MEKENZIE
2
NAME RILEY
3
COUNTRY United States
4
COUNTRY United States
5
AGE Age 31
6
STATS 5'4" | 155 lbs
7
PROFILE View Profile
8
POINTS 228
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 26
1
NAME DANI
2
NAME SPEEGLE
3
COUNTRY United States
4
COUNTRY United States
5
AGE Age 25
6
STATS 5'6" | 168 lbs
7
PROFILE View Profile
8
POINTS 226
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 27
1
NAME COLLEEN
2
NAME FOTSCH
3
COUNTRY United States
4
COUNTRY United States
5
AGE Age 29
6
STATS 5'8" | 167 lbs
7
PROFILE View Profile
8
POINTS 222
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 28
1
NAME CAMILLA
2
NAME SALOMONSSON HELLMAN
3
COUNTRY Sweden
4
COUNTRY Sweden
5
AGE Age 28
6
STATS 5'5" | 149 lbs
7
PROFILE View Profile
8
POINTS 208
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 29
1
NAME COURTNEY
2
NAME HALEY
3
COUNTRY Australia
4
COUNTRY Australia
5
AGE Age 24
6
STATS 5'5" | 152 lbs
7
PROFILE View Profile
8
POINTS 191
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 30
1
NAME PAIGE
2
NAME SEMENZA
3
COUNTRY United States
4
COUNTRY United States
5
AGE Age 27
6
STATS 5'3" | 143 lbs
7
PROFILE View Profile
8
POINTS 171
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 31
1
NAME EMMA
2
NAME TALL
3
COUNTRY Sweden
4
COUNTRY Sweden
5
AGE Age 27
6
STATS 5'6" | 154 lbs
7
PROFILE View Profile
8
POINTS 168
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 32
1
NAME CARRIE
2
NAME BEAMER
3
COUNTRY United States
4
COUNTRY United States
5
AGE Age 27
6
STATS 5'3" | 135 lbs
7
PROFILE View Profile
8
POINTS 167
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 33
1
NAME CAROLE
2
NAME CASTELLANI
3
COUNTRY France
4
COUNTRY France
5
AGE Age 30
6
STATS 5'7" | 152 lbs
7
PROFILE View Profile
8
POINTS 156
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 34
1
NAME LINDSAY
2
NAME VAUGHAN
3
COUNTRY United States
4
COUNTRY United States
5
AGE Age 34
6
STATS 5'8" | 154 lbs
7
PROFILE View Profile
8
POINTS 152
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 35
1
NAME ALESSIA JOY
2
NAME W√ÑLCHLI
3
COUNTRY Switzerland
4
COUNTRY Switzerland
5
AGE Age 25
6
STATS 5'6" | 146 lbs
7
PROFILE View Profile
8
POINTS 152
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 36
1
NAME SIMONA
2
NAME QUINTANA
3
COUNTRY Chile
4
COUNTRY Chile
5
AGE Age 23
6
STATS 5'6" | 143 lbs
7
PROFILE View Profile
8
POINTS 141
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 37
1
NAME HANNA
2
NAME KARLSSON
3
COUNTRY Sweden
4
COUNTRY Sweden
5
AGE Age 26
6
STATS 5'9" | 176 lbs
7
PROFILE View Profile
8
POINTS 132
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 38
1
NAME ODDR√öN EIK
2
NAME GYLFADOTTIR
3
COUNTRY Iceland
4
COUNTRY Iceland
5
AGE Age 30
6
STATS 5'4" | 128 lbs
7
PROFILE View Profile
8
POINTS 125
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 39
1
NAME CHERYL
2
NAME NASSO
3
COUNTRY United States
4
COUNTRY United States
5
AGE Age 34
6
STATS 5'4" | 125 lbs
7
PROFILE View Profile
8
POINTS 122
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 40
1
NAME RACHEL
2
NAME GARIBAY
3
COUNTRY United States
4
COUNTRY United States
5
AGE Age 27
6
STATS 0'5" | 130 lbs
7
PROFILE View Profile
8
POINTS 100
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 41
1
NAME MICHELLE
2
NAME MERAND
3
COUNTRY South Africa
4
COUNTRY South Africa
5
AGE Age 30
6
STATS 5'2" | 132 lbs
7
PROFILE View Profile
8
POINTS 98
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 42
1
NAME KSENIJA
2
NAME KECMAN
3
COUNTRY Bosnia and Herzegovina
4
COUNTRY Bosnia and Herzegovina
5
AGE Age 30
6
STATS 5'10" | 152 lbs
7
PROFILE View Profile
8
POINTS 90
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK DQ
1
NAME KATIE
2
NAME TROMBETTA
3
COUNTRY United States
4
COUNTRY United States
5
AGE Age 28
6
STATS 5'3" | 148 lbs
7
PROFILE View Profile
8
POINTS 89
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 43
1
NAME LEONIE
2
NAME HENRICH
3
COUNTRY Netherlands
4
COUNTRY Netherlands
5
AGE Age 25
6
STATS 5'7" | 157 lbs
7
PROFILE View Profile
8
POINTS 86
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 44
1
NAME CARMEN
2
NAME BOSMANS
3
COUNTRY Belgium
4
COUNTRY Belgium
5
AGE Age 30
6
STATS 5'6" | 154 lbs
7
PROFILE View Profile
8
POINTS 80
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 45
1
NAME JACQUELINE
2
NAME DAHLSTR√òM
3
COUNTRY Norway
4
COUNTRY Norway
5
AGE Age 27
6
STATS 5'6" | 148 lbs
7
PROFILE View Profile
8
POINTS 77
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 46
1
NAME THELMA
2
NAME CHRISTOFOROU
3
COUNTRY Cyprus
4
COUNTRY Cyprus
5
AGE Age 32
6
STATS 5'6" | 143 lbs
7
PROFILE View Profile
8
POINTS 74
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 47
1
NAME CAROL
2
NAME COLLING-ROMERO
3
COUNTRY Paraguay
4
COUNTRY Paraguay
5
AGE Age 26
6
STATS 5'2" | 123 lbs
7
PROFILE View Profile
8
POINTS 71
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 48
1
NAME MCKENZIE
2
NAME FLINCHUM
3
COUNTRY United States
4
COUNTRY United States
5
AGE Age 27
6
STATS 5'5" | 147 lbs
7
PROFILE View Profile
8
POINTS 69
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 49
1
NAME LISA
2
NAME EBLE
3
COUNTRY Germany
4
COUNTRY Germany
5
AGE Age 28
6
STATS 5'3" | 145 lbs
7
PROFILE View Profile
8
POINTS 54
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 50
1
NAME ERIN
2
NAME VANDENDRIESSCHE
3
COUNTRY United States
4
COUNTRY United States
5
AGE Age 28
6
STATS 5'7" | 145 lbs
7
PROFILE View Profile
8
POINTS 48
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 51
1
NAME ANASTASIYA
2
NAME GANINA
3
COUNTRY Russian Federation
4
COUNTRY Russian Federation
5
AGE Age 34
6
STATS 5'7" | 152 lbs
7
PROFILE View Profile
8
POINTS 46
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 52
1
NAME NEYRAN
2
NAME GUNELI
3
COUNTRY Turkey
4
COUNTRY Turkey
5
AGE Age 37
6
STATS 5'7" | 150 lbs
7
PROFILE View Profile
8
POINTS 45
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 53
1
NAME BROOKE
2
NAME HAAS
3
COUNTRY United States
4
COUNTRY United States
5
AGE Age 30
6
STATS 5'3" | 152 lbs
7
PROFILE View Profile
8
POINTS 44
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 54
1
NAME BRENDA
2
NAME CASTRO
3
COUNTRY Mexico
4
COUNTRY Mexico
5
AGE Age 30
6
STATS 5'4" | 138 lbs
7
PROFILE View Profile
8
POINTS 43
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 55
1
NAME EMILIA
2
NAME LEPPANEN
3
COUNTRY Finland
4
COUNTRY Finland
5
AGE Age 32
6
STATS 5'5" | 150 lbs
7
PROFILE View Profile
8
POINTS 40
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 56
1
NAME SABRINA
2
NAME CARON
3
COUNTRY France
4
COUNTRY France
5
AGE Age 27
6
STATS 5'3" | 128 lbs
7
PROFILE View Profile
8
POINTS 36
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 57
1
NAME KATELIN
2
NAME VAN ZYL
3
COUNTRY Australia
4
COUNTRY Australia
5
AGE Age 27
6
STATS 5'7" | 150 lbs
7
PROFILE View Profile
8
POINTS 36
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 58
1
NAME RALITZA
2
NAME KOTERLITZOVA
3
COUNTRY Bulgaria
4
COUNTRY Bulgaria
5
AGE Age 30
6
STATS 5'3" | 135 lbs
7
PROFILE View Profile
8
POINTS 35
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 59
1
NAME TAMARA
2
NAME ZULIM
3
COUNTRY Croatia
4
COUNTRY Croatia
5
AGE Age 35
6
STATS 5'7" | 132 lbs
7
PROFILE View Profile
8
POINTS 35
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 60
1
NAME MARIA CAMILA
2
NAME QUINTERO
3
COUNTRY Colombia
4
COUNTRY Colombia
5
AGE Age 23
6
STATS 5'1" | 130 lbs
7
PROFILE View Profile
8
POINTS 34
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 61
1
NAME TAYLOR
2
NAME STREID
3
COUNTRY United States
4
COUNTRY United States
5
AGE Age 28
6
STATS 5'6" | 140 lbs
7
PROFILE View Profile
8
POINTS 32
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 62
1
NAME NICOLE
2
NAME PETTEL
3
COUNTRY Israel
4
COUNTRY Israel
5
AGE Age 27
6
STATS 5'3" | 150 lbs
7
PROFILE View Profile
8
POINTS 28
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 63
1
NAME RENATA
2
NAME PIMENTEL
3
COUNTRY Brazil
4
COUNTRY Brazil
5
AGE Age 36
6
STATS 5'9" | 161 lbs
7
PROFILE View Profile
8
POINTS 28
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 64
1
NAME LYNDSAY
2
NAME MURRAY
3
COUNTRY Trinidad and Tobago
4
COUNTRY Trinidad and Tobago
5
AGE Age 29
6
STATS 5'7" | 128 lbs
7
PROFILE View Profile
8
POINTS 27
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 65
1
NAME AKIKO
2
NAME KAMITANI
3
COUNTRY Japan
4
COUNTRY Japan
5
AGE Age 30
6
STATS 5'1" | 115 lbs
7
PROFILE View Profile
8
POINTS 26
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 66
1
NAME VERA
2
NAME VALDEZ
3
COUNTRY Guatemala
4
COUNTRY Guatemala
5
AGE Age 30
6
STATS 5'4" | 130 lbs
7
PROFILE View Profile
8
POINTS 21
9
SPLIT_TRIPLET CUT (--)
10
CLEAN CUT (--)
11
SWIM_PADDLE CUT (--)
12
RINGER_1 CUT (--)
13
RINGER_2 CUT (--)
14
THE_STANDARD CUT (--)
0
RANK 67
1
NAME JACKY
2
NAME SCHMITT
3
COUNTRY Luxembourg
4
COUNTRY Luxembourg
5
AGE Age 25
6
STATS 5'5" | 134 lbs
7

In [270]:
display(games_data_1)

,RANK,NAME,POINTS,FIRST_CUT,SECOND_CUT,RUCK,SPRINT_COUPLET,MARY,SPRINT,SPLIT_TRIPLET,CLEAN,SWIM_PADDLE,RINGER_1,RINGER_2,THE_STANDARD
0,2,TIA-CLAIR TOOMEY,1071,1st (16:56.63),12th (6:59.75),2nd (27:11.18),12th (1:47.66),4th (656 rep),3rd (18 pt),1st (14:07.10),1st (265.0 lb),1st (25:12.25),4th (5:44.63),3rd (3:14.03),1st (8:25.09)
1,3,KRISTIN HOLTE,876,7th (CAP+2),6th (6:43.32),3rd (27:12.24),19th (2:00.54),2nd (675 rep),1st (20 pt),5th (16:10.92),5th (225.0 lb),6th (30:17.62),3rd (5:43.70),7th (3:49.14),4th (9:38.26)
2,4,JAMIE GREENE,851,3rd (19:00.67),24th (7:41.94),22nd (30:30.81),4th (1:35.70),3rd (664 rep),5th (16 pt),4th (15:32.03),6th (220.0 lb),4th (28:32.16),6th (5:52.21),6th (3:35.62),2nd (9:14.71)
3,5,KATR√çN TANJA DAVIDSDOTTIR,784,21st (CAP+9),10th (6:58.42),5th (27:52.61),26th (2:07.84),11th (590 rep),9th (12 pt),3rd (15:10.09),4th (230.0 lb),8th (32:36.98),1st (5:09.87),1st (2:53.29),9th (10:56.22)
4,6,KARISSA PEARCE,714,2nd (18:16.35),3rd (6:32.22),13th (29:25.99),18th (1:59.41),1st (695 rep),16th (5 pt),2nd (14:34.71),8th (0.0 lb),7th (31:34.67),7th (5:54.13),10th (CAP+8),5th (9:47.12)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124,126,CINGIWE CIEGY SERU,-42,117T (CAP+43),CUT (--),CUT (--),CUT (--),CUT (--),CUT (--),CUT (--),CUT (--),CUT (--),CUT (--),CUT (--),CUT (--)
125,127,MIRIAM TORRA,-42,117T (CAP+43),CUT (--),CUT (--),CUT (--),CUT (--),CUT (--),CUT (--),CUT (--),CUT (--),CUT (--),CUT (--),CUT (--)
126,128,TAMARA TRUMBETA≈†,-42,117T (CAP+43),CUT (--),CUT (--),CUT (--),CUT (--),CUT (--),CUT (--),CUT (--),CUT (--),CUT (--),CUT (--),CUT (--)
127,129,KESHINI VITHARANA,-42,117T (CAP+43),CUT (--),CUT (--),CUT (--),CUT (--),CUT (--),CUT (--),CUT (--),CUT (--),CUT (--),CUT (--),CUT (--)
128,1,MELANIE YIP WOON SUN,-42,117T (CAP+43),CUT (--),CUT (--),CUT (--),CUT (--),CUT (--),CUT (--),CUT (--),CUT (--),CUT (--),CUT (--),CUT (--)

In [275]:
games_data_1[['first_cut_pos', 'first_cut_time', 't1', 't2']] = games_data_1.FIRST_CUT.str.split(" ", expand=True,)
games_data_1[['second_cut_pos', 'second_cut_time', 't1', 't2']] = games_data_1.SECOND_CUT.str.split(" ", expand=True,)
games_data_1[['ruck_pos', 'ruck_time', 't1', 't2']] = games_data_1.RUCK.str.split(" ", expand=True,)
games_data_1[['sprint_couplet_pos', 'sprint_couplet_time', 't1', 't2']] = games_data_1.SPRINT_COUPLET.str.split(" ", expand=True,)
games_data_1[['mary_pos', 'mary_time', 't1', 't2', 't3', 't4']] = games_data_1.MARY.str.split(" ", expand=True,)
games_data_1[['sprint_pos', 'sprint_time', 't1', 't2', 't3', 't4']] = games_data_1.SPRINT.str.split(" ", expand=True,)
games_data_1[['split_triplet_pos', 'split_triplet_time']] = games_data_1.SPLIT_TRIPLET.str.split(" ", expand=True,)
games_data_1[['clean_pos', 'clean_time', 't1']] = games_data_1.CLEAN.str.split(" ", expand=True,)
games_data_1[['swim_paddle_pos', 'swim_paddle_time']] = games_data_1.SWIM_PADDLE.str.split(" ", expand=True,)
games_data_1[['ringer_1_pos', 'ringer_1_time']] = games_data_1.RINGER_1.str.split(" ", expand=True,)
games_data_1[['ringer_2_pos', 'ringer_2_time']] = games_data_1.RINGER_2.str.split(" ", expand=True,)
games_data_1[['the_standard_pos', 'the_standard_time']] = games_data_1.THE_STANDARD.str.split(" ", expand=True,)

In [274]:
games_data_1.SPRINT.str.split(" ", expand=True,)

        0     1     2     3     4     5
0     3rd   (18   pt)  None  None  None
1     1st   (20   pt)  None  None  None
2     5th   (16   pt)  None  None  None
3     9th   (12   pt)  None  None  None
4    16th    (5   pt)  None  None  None
..    ...   ...   ...   ...   ...   ...
124   CUT  (--)  None  None  None  None
125   CUT  (--)  None  None  None  None
126   CUT  (--)  None  None  None  None
127   CUT  (--)  None  None  None  None
128   CUT  (--)  None  None  None  None

[129 rows x 6 columns]

In [276]:
score_dat = games_data_1#[['RANK', 'NAME', 'POINTS', 'first_cut_time', 'second_cut_time', 'ruck_time', 'sprint_couplet_time', 'mary_time', 'sprint_time', 'split_triplet_time', 'clean_time', 'swim_paddle_time', 'ringer_1_time', "ringer_2_time", "the_standard_time"]]

In [277]:
cols_to_check = score_dat.columns
score_dat[cols_to_check] = score_dat[cols_to_check].replace({'\(':''}, regex=True)
score_dat[cols_to_check] = score_dat[cols_to_check].replace({'\)':''}, regex=True)

In [278]:
score_dat_stored = score_dat

In [279]:
score_dat_stored

,RANK,NAME,POINTS,FIRST_CUT,SECOND_CUT,RUCK,SPRINT_COUPLET,MARY,SPRINT,SPLIT_TRIPLET,...,clean_pos,clean_time,swim_paddle_pos,swim_paddle_time,ringer_1_pos,ringer_1_time,ringer_2_pos,ringer_2_time,the_standard_pos,the_standard_time
0,2,TIA-CLAIR TOOMEY,1071,1st 16:56.63,12th 6:59.75,2nd 27:11.18,12th 1:47.66,4th 656 rep,3rd 18 pt,1st 14:07.10,...,1st,265.0,1st,25:12.25,4th,5:44.63,3rd,3:14.03,1st,8:25.09
1,3,KRISTIN HOLTE,876,7th CAP+2,6th 6:43.32,3rd 27:12.24,19th 2:00.54,2nd 675 rep,1st 20 pt,5th 16:10.92,...,5th,225.0,6th,30:17.62,3rd,5:43.70,7th,3:49.14,4th,9:38.26
2,4,JAMIE GREENE,851,3rd 19:00.67,24th 7:41.94,22nd 30:30.81,4th 1:35.70,3rd 664 rep,5th 16 pt,4th 15:32.03,...,6th,220.0,4th,28:32.16,6th,5:52.21,6th,3:35.62,2nd,9:14.71
3,5,KATR√çN TANJA DAVIDSDOTTIR,784,21st CAP+9,10th 6:58.42,5th 27:52.61,26th 2:07.84,11th 590 rep,9th 12 pt,3rd 15:10.09,...,4th,230.0,8th,32:36.98,1st,5:09.87,1st,2:53.29,9th,10:56.22
4,6,KARISSA PEARCE,714,2nd 18:16.35,3rd 6:32.22,13th 29:25.99,18th 1:59.41,1st 695 rep,16th 5 pt,2nd 14:34.71,...,8th,0.0,7th,31:34.67,7th,5:54.13,10th,CAP+8,5th,9:47.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124,126,CINGIWE CIEGY SERU,-42,117T CAP+43,CUT --,CUT --,CUT --,CUT --,CUT --,CUT --,...,CUT,--,CUT,--,CUT,--,CUT,--,CUT,--
125,127,MIRIAM TORRA,-42,117T CAP+43,CUT --,CUT --,CUT --,CUT --,CUT --,CUT --,...,CUT,--,CUT,--,CUT,--,CUT,--,CUT,--
126,128,TAMARA TRUMBETA≈†,-42,117T CAP+43,CUT --,CUT --,CUT --,CUT --,CUT --,CUT --,...,CUT,--,CUT,--,CUT,--,CUT,--,CUT,--
127,129,KESHINI VITHARANA,-42,117T CAP+43,CUT --,CUT --,CUT --,CUT --,CUT --,CUT --,...,CUT,--,CUT,--,CUT,--,CUT,--,CUT,--
128,1,MELANIE YIP WOON SUN,-42,117T CAP+43,CUT --,CUT --,CUT --,CUT --,CUT --,CUT --,...,CUT,--,CUT,--,CUT,--,CUT,--,CUT,--

In [280]:
time_cols = ['first_cut_time', 'second_cut_time', 'ruck_time', 'sprint_couplet_time', 'mary_time', 'split_triplet_time', 'swim_paddle_time', 'ringer_1_time', "ringer_2_time", "the_standard_time"]
score_dat = score_dat_stored
score_dat[time_cols] = score_dat[time_cols].replace({'\.':''}, regex=True)
score_dat[time_cols] = score_dat[time_cols].replace({'\:':'.'}, regex=True)

In [281]:
score_dat.to_csv('/Users/thomasnicholson/Documents/games_data_w.csv', index=False)

In [228]:
for column in time_cols:
    current_col = score_dat[column]
    current_col = pd.to_numeric(current_col, errors='coerce')
    time_cap = math.ceil(current_col.dropna().max())
    print("%s: %s" % (column, time_cap))

first_cut_time: 20
second_cut_time: 10
ruck_time: 33
sprint_couplet_time: 3
mary_time: 677
split_triplet_time: 20
swim_paddle_time: 36
ringer_1_time: 6
ringer_2_time: 5
the_standard_time: 11

In [230]:
time_cuts = {'first_cut_time': 20, 'second_cut_time': 10, 'ruck_time': 40, 'sprint_couplet_time': 6, 'mary_time': 20, 'split_triplet_time': 20, 'swim_paddle_time': 50, 'ringer_1_time': 7, "ringer_2_time": 5, "the_standard_time": 12}

In [237]:
for column in time_cols:
    print(time_cuts[column])

20
10
40
6
20
20
50
7
5
12

In [242]:
score_dat[['first_cut_1', 'first_cut_cap_score']] = score_dat.first_cut_time.str.split("+", expand=True,)
score_dat[['second_cut_1', 'second_cut_cap_score']] = score_dat.second_cut_time.str.split("+", expand=True,)
# score_dat[['ruck_1', 'ruck_cap_score']] = score_dat.ruck_time.str.split("+", expand=True,)
# score_dat[['sprint_couplet_1', 'sprint_couplet_cap_score']] = score_dat.sprint_couplet_time.str.split("+", expand=True,)
score_dat[['split_triplet_1', 'split_triplet_cap_score']] = score_dat.split_triplet_time.str.split("+", expand=True,)
# score_dat[['swim_paddle_1', 'swim_paddle_cap_score']] = score_dat.swim_paddle_time.str.split("+", expand=True,)
# score_dat[['ringer_1_1', 'ringer_1_cap_score']] = score_dat.ringer_1_time.str.split("+", expand=True,)
score_dat[['ringer_2_1', 'ringer_2_cap_score']] = score_dat.ringer_2_time.str.split("+", expand=True,)
score_dat[['the_standard_1', 'the_standard_cap_score']] = score_dat.the_standard_time.str.split("+", expand=True,)

score_dat

,RANK,NAME,POINTS,first_cut_time,second_cut_time,ruck_time,sprint_couplet_time,mary_time,sprint_time,split_triplet_time,...,first_cut_1,first_cut_cap_score,second_cut_1,second_cut_cap_score,split_triplet_1,split_triplet_cap_score,ringer_2_1,ringer_2_cap_score,the_standard_1,the_standard_cap_score
0,2,MATHEW FRASER,984,150770,53702,255009,15008,675,6,153660,...,150770,None,53702,None,153660,None,30694,None,80578,None
1,3,NOAH OHLSEN,949,170214,61301,262777,12840,677,18,163590,...,170214,None,61301,None,163590,None,33198,None,80997,None
2,4,BJ√ñRGVIN KARL GU√êMUNDSSON,888,160851,70018,254944,14967,598,19,164275,...,160851,None,70018,None,164275,None,31561,None,82280,None
3,5,SCOTT PANCHIK,795,160595,61012,275770,14568,645,14,190550,...,160595,None,61012,None,190550,None,32595,None,83565,None
4,6,JAMES NEWBURY,728,162119,60809,244793,15274,515,12,171746,...,162119,None,60809,None,171746,None,44495,None,105869,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136,138,ENRIC CLOSA,-63,CAP+42,--,--,--,--,--,--,...,CAP,42,--,None,--,None,--,None,--,None
137,139,KILA KILAVERAVE,-63,CAP+42,--,--,--,--,--,--,...,CAP,42,--,None,--,None,--,None,--,None
138,140,KEITH NHAN,-63,CAP+42,--,--,--,--,--,--,...,CAP,42,--,None,--,None,--,None,--,None
139,141,FREDERIK AEGIDIUS,CUT --,--,--,--,--,--,NaN,--,...,--,None,--,None,--,None,--,None,NaN,NaN
140,1,ASLAM AL SHUKAILI,WD --,--,--,--,--,--,NaN,--,...,--,None,--,None,--,None,--,None,NaN,NaN

In [317]:
data_1 = open("/Users/thomasnicholson/Documents/games_data_m_2018_1.txt", 'r')
data_2 = open("/Users/thomasnicholson/Documents/games_data_m_2018_2.txt", 'r')
data_3 = open("/Users/thomasnicholson/Documents/games_data_m_2018_3.txt", 'r')

In [318]:
numRows = 40
numCols  = 17
data_1.seek(0)
data_2.seek(0)
games_data_1 = pd.DataFrame(index=range(numRows),columns=range(numCols))
games_data_1.columns = ['RANK', 'NAME', 'POINTS', 'Crit', 'Muscle_Ups', 
                        'Crossfit_Total', 'Marathon_Row', 'The_Battleground', 'Clean_and_Jerk_Ladder', 'Fibonacci',
                        'Triplus', 'Chaos', 'Bicouplet_1', 'Bicouplet_2', 'Two_Stroke_Pull', 'Handstand_walk', 'Aeneas']
counter = 0
position = 0
columns_by_line = ['RANK', 'NAME', 'NAME', 'COUNTRY', 'AGE', 'STATS', 'PROFILE', 
                   'POINTS','Crit', 'Muscle_Ups', 
                        'Crossfit_Total', 'Marathon_Row', 'The_Battleground', 'Clean_and_Jerk_Ladder', 'Fibonacci',
                        'Triplus', 'Chaos', 'Bicouplet_1', 'Bicouplet_2', 'Two_Stroke_Pull', 'Handstand_walk', 'Aeneas']
for line in data_1:
    line = line.rstrip()
    if 'pts' in line:
        continue
    rank = counter + 1
    rank_num = counter - 1
    rank = str(rank)

    
    if line == rank:
#         print(line)
        counter += 1
        position = 0
    if counter == 0:
        continue
#     print(position)
#     print(line)
#     print('%s %s' % (columns_by_line[position] ,line))
    if columns_by_line[position] in games_data_1.columns:
        col_num = games_data_1.columns.get_loc(columns_by_line[position])
        if pd.isna(games_data_1.iloc[rank_num,col_num]):
            games_data_1.iloc[rank_num,col_num] = line
        else:
            games_data_1.iloc[rank_num,col_num] = '%s %s' %(games_data_1.iloc[rank_num,col_num],line)
    position += 1
    if position == 14:
        position = 0

columns_by_line = ['RANK', 'NAME', 'NAME', 'COUNTRY', 'AGE', 'STATS', 'PROFILE', 
                   'POINTS', 'Fibonacci',
                        'Triplus', 'Chaos', 'Bicouplet_1', 'Bicouplet_2', 'Two_Stroke_Pull', 'Handstand_walk', 'Aeneas']      
counter = 0
position = 0
for line in data_2:
    line = line.rstrip()
    if 'pts' in line:
        continue
    rank = counter + 1
    rank_num = counter - 1
    rank = str(rank)

    
    if line == rank:
#         print(line)
        counter += 1
        position = 0
    if counter == 0:
        continue
#     print(position)
#     print(line)
#     print('%s %s' % (columns_by_line[position] ,line))
    if columns_by_line[position] in games_data_1.columns:
        col_num = games_data_1.columns.get_loc(columns_by_line[position])
        if pd.isna(games_data_1.iloc[rank_num,col_num]):
            games_data_1.iloc[rank_num,col_num] = line
    position += 1
    if position == 14:
        position = 0

        
columns_by_line = ['RANK', 'NAME', 'NAME', 'COUNTRY', 'AGE', 'STATS', 'PROFILE', 
                   'POINTS', 'Chaos', 'Bicouplet_1', 'Bicouplet_2', 'Two_Stroke_Pull', 'Handstand_walk', 'Aeneas']          
counter = 0
position = 0
for line in data_3:
    line = line.rstrip()
    if 'pts' in line:
        continue
    rank = counter + 1
    rank_num = counter - 1
    rank = str(rank)

    
    if line == rank:
#         print(line)
        counter += 1
        position = 0
    if counter == 0:
        continue
#     print(position)
#     print(line)
#     print('%s %s' % (columns_by_line[position] ,line))
    if columns_by_line[position] in games_data_1.columns:
        col_num = games_data_1.columns.get_loc(columns_by_line[position])
        if pd.isna(games_data_1.iloc[rank_num,col_num]):
            games_data_1.iloc[rank_num,col_num] = line
    position += 1
    if position == 14:
        position = 0

In [319]:
games_data_1

,RANK,NAME,POINTS,Crit,Muscle_Ups,Crossfit_Total,Marathon_Row,The_Battleground,Clean_and_Jerk_Ladder,Fibonacci,Triplus,Chaos,Bicouplet_1,Bicouplet_2,Two_Stroke_Pull,Handstand_walk,Aeneas
0,2,MATHEW FRASER,1162,4th (18:36.55),3rd (2:00.16),8th (1215 lb),11th (2:48:36.00),2nd (8:49.40),7th (7 pt),1st (4:54.84),4th (27:24.58),9th (9:47.81),2nd (3:10.36),4th (4:10.77),4th (14:06.03),3rd (1:44.99),1st (3:56.47)
1,3,PATRICK VELLNER,942,35th (20:52.66),9th (2:12.69),2nd (1250 lb),5th (2:47:13.00 ),4th (8:54.79),11th (11 pt),4th (5:51.65),21st (30:24.98),1st (9:19.86),5th (3:16.90),10th (4:30.13),11th (14:22.74),10th (2:20.07),7th (4:50.76)
2,4,LUKAS H√ñGBERG,886,3rd (18:36.28),12th (2:22.36),11T (1190 lb),2nd (2:44:33.00 ),3rd (8:51.20),10th (10 pt),7T (CAP+1),23rd (30:34.44),4th (9:40.94),11th (3:31.68),34th (5:39.87),1st (13:36.40),24th (3:34.68),15th (5:29.05)
3,5,BRENT FIKOWSKI,886,9th (18:39.05),13th (2:28.15),20T (1150 lb),4th (2:47:03.00 ),7th (9:26.42),8th (8 pt),5T (CAP),2nd (26:52.44),10th (9:48.21),29th (3:53.76),18th (4:37.66),2nd (13:55.60),27th (3:49.76),4th (4:42.17)
4,6,BJ√ñRGVIN KARL GU√êMUNDSSON,834,6th (18:37.24),10th (2:16.87),15th (1185 lb),14th (2:51:17.00),6th (9:24.68),21st (21 pt),12th (CAP+5),10th (27:55.80),8th (9:45.99),9th (3:29.14),12th (4:32.34),15th (14:37.00),7th (2:12.40),12th (5:12.11)
5,7,NOAH OHLSEN,786,30th (20:08.10),11th (2:21.67),11T (1190 lb),24th (2:57:12.00),10th (9:35.18),15th (15 pt),2nd (5:22.39),12th (28:17.31),11th (9:52.58),4th (3:13.89),24th (4:50.27),24th (15:19.91),9th (2:15.65),3rd (4:25.26)
6,8,COLE SAGER,760,13th (18:44.34),5th (2:01.85),17T (1165 lb),3rd (2:46:55.00 ),1st (8:35.01),33T (33 pt),22T (CAP+15),20th (29:32.05),5th (9:41.31),25th (3:51.08),32nd (5:28.64),28th (15:43.04),11th (2:22.40),2nd (4:07.11)
7,9,RASMUS ANDERSEN,734,7T (18:37.38),16th (2:34.30),31T (1095 lb),7th (2:47:50.00 ),35T (CAP+4),18th (18 pt),35T (CAP+29),7th (27:36.91),18th (10:29.01),18th (3:41.24),1st (4:03.93),6th (14:14.70),6th (2:04.07),16th (5:38.87)
8,10,WILLY GEORGES,728,11th (18:43.29),15th (2:32.13),5T (1230 lb),20th (2:54:16.00),14th (9:48.52),16th (16 pt),22T (CAP+15),14th (28:34.23),20th (10:31.78),1st (3:03.67),2nd (4:05.72),12th (14:33.16),37T (CAP+2),32nd (7:34.16)
9,11,CODY ANDERSON,712,36th (20:53.50),4th (2:01.28),28T (1115 lb),33rd (3:03:40.00),16th (9:52.65),19th (19 pt),7T (CAP+1),27th (31:03.06),6th (9:41.95),3rd (3:11.41),7th (4:17.51),38th (16:49.84),1st (1:29.42),13th (5:17.83)
10,12,SCOTT PANCHIK,694,37th (20:53.51),28th (2:58.57),4th (1235 lb),22nd (2:56:16.00),18th (10:02.80),4th (4 pt),13T (CAP+6),19th (29:07.94),13th (9:58.78),6th (3:17.83),5th (4:11.49),32nd (15:58.83),25th (3:44.83),9th (4:58.94)
11,13,BEN SMITH,684,12th (18:44.23),18th (2:34.93),26th (1135 lb),13th (2:50:18.00),28th (10:56.46),5th (5 pt),32nd (CAP+22),11th (28:08.37),32nd (11:38.95),23rd (3:47.88),3rd (4:05.98),23rd (15:16.65),4th (1:49.73),8th (4:54.28)
12,14,ALEX ANDERSON,676,32nd (20:10.42),26th (2:56.18),11T (1190 lb),30th (3:00:43.00),13th (9:44.16),13th (13 pt),20th (CAP+13),13th (28:20.97),3rd (9:38.79),7th (3:20.98),8th (4:17.77),13th (14:33.80),35th (CAP+1),10th (5:01.09)
13,15,DEAN LINDER-LEIGHTON,668,16th (18:57.11),14th (2:30.30),23T (1145 lb),16th (2:52:23.00),26th (10:44.10),25th (25 pt),5T (CAP),1st (26:37.51),19th (10:31.31),16th (3:39.40),11th (4:32.12),22nd (15:12.85),20th (3:08.25),28th (6:42.69)
14,16,LOGAN COLLINS,652,29th (20:01.25),1st (1:46.00),17T (1165 lb),35th (3:05:48.00),20th (10:13.30),32nd (32 pt),3rd (5:48.06),17th (29:07.33),34T (CAP+1),8th (3:27.61),19th (4:38.29),37th (16:31.53),5th (2:03.16),6th (4:49.37)
15,17,ADRIAN MUNDWILER,652,1st (18:32.24),7th (2:10.78),23T (1145 lb),15th (2:51:27.00),12th (9:37.19),27th (27 pt),17th (CAP+9),31st (32:01.22),22nd (10:39.72),13th (3:35.10),21st (4:41.09),18th (15:03.72),21st (3:16.12),20th (6:06.27)
16,18,LUKAS ESSLINGER,648,23rd (19:45.71),22nd (2:48.44),3rd (1245 lb),1st (2:43:50.00),11th (9:36.00),22nd (22 pt),35T (CAP+29),26th (30:59.29),21st (10:34.55),21st (3:43.89),26th (4:55.10),8th (14:20.60),23rd (3:32.28),14th (5:20.31)
17,19,JAMES NEWBURY,616,2nd (18:35.14),30th (3:06.24),38th (975 lb),8th (2:47:59.00 ),5th (9:11.87),30th (30 pt),30th (CAP+18),3rd (26:52.66),16th (10:26.20),17th (3:40.37),35th (5:43.16),17th (14:49.80),14th (2:38.21),30th (7:03.90)
18,20,SAXON PANCHIK,602,27th (19:57.50),17th (2:34.39),27th (1125 lb),34th (3:05:35.00),23rd (10:23.88),14th (14 pt),22T (CAP+15),8th (27:37.12),2nd (9:37.01),27th (3:52.83),13th (4:32.63),26th (15:36.00),12th (2:23.06),18th (5:43.70)
19,21,NICHOLAS URANKAR,590,15th (18:46.91),24th (2:52.47),5T (1230 lb),23rd (2:56:47.00),30th (CAP+1),1st (1 pt),21st (CAP+14),30th (31:33.31),26th (10:46.68),33rd (4:06.12),14th (4:35.46),29th (15:45.00),19th (2:56.75),11th (5:05.11)
20,22,FREDERICK AEGIDIUS,586,7T (18:37.38),23rd (2:49.22),19th (1155 lb),9th (2:48:08.00 ),15th (9:51.26),33T (33 pt),37T (CAP+31),15th (29:03.03),14th (10:04.47),36th (4:16.73),27th (5:09.77),5th (14:13.00),36th (CAP+1),5th (4:47.32)
21,23,SEAN SWEENEY,580,19th (19:41.96),20th (2:47.22),25th (1140 lb),25th (2:57:36.00),22nd (10:18.00),31st (31 pt),10T (CAP+4),6th (27:32.67),27th (10:47.41),15th (3:37.04),6th (4:16.60),21st (15:11.90),30th (CAP+1),21st (6:11.05)
22,24,ROGELIO GAMBOA,578,25th (19:48.78),25th (2:54.23),11T (1190 lb),6th (2:47:29.00 ),25th (10:35.18),6th (6 pt),28th (CAP+16),32nd (32:26.33),23rd (10:39.80),12th (3:34.59),16th (4:36.72),27th (15:41.80),16th (2:46.91),27th (6:38.90)
23,25,KHAN PORTER,558,31st (20:08.13),36th (3:30.52),28T (1115 lb),19th (2:53:57.00),19th (10:08.39),28th (28 pt),13T (CAP+6),5th (27:30.82),7th (9:43.27),24th (3:50.70),17th (4:37.56),9th (14:22.13),37T (CAP+2),17th (5:41.19)
24,26,ALEC SMITH,548,28th (19:59.40),6th (2:07.87),33rd (1080 lb),18th (2:53:47.00),21st (10:14.38),12th (12 pt),18T (CAP+10),29th (31:21.48),37th (CAP+2),14th (3:36.86),22nd (4:44.03),33T (16:07.00 ),2nd (1:38.60),26th (6:33.42)
25,27,ELLIOT SIMMONDS,530,21st (19:42.50),29th (2:59.49),34T (1040 lb),12th (2:49:13.00),9th (9:33.32),37T (37 pt),22T (CAP+15),9th (27:53.90),17th (10:28.74),31st (4:00.75),25th (4:53.84),7th (14:16.19),28th (3:55.13),19th (5:59.83)
26,28,CRAIG KENNEY,516,10th (18:40.05),32nd (3:14.39),20T (1150 lb),17th (2:53:20.00),29th (10:56.80),17th (17 pt),10T (CAP+4),25th (30:58.29),25th (10:46.64),30th (3:55.33),20th (4:38.86),25th (15:21.00),18th (2:52.89),24th (6:17.44)
27,29,JOHN COLTEY,486,26th (19:57.01),27th (2:56.70),9th (1210 lb),26th (2:57:39.00),35T (CAP+4),20th (20 pt),9th (CAP+2),28th (31:07.10),33rd (11:49.82),19th (3:41.72),31st (5:24.98),19th (15:06.77),8th (2:15.51),31st (7:06.45)
28,30,TIM PAULSON,480,20th (19:42.00),35th (3:30.01),16th (1175 lb),32nd (3:02:09.00),27th (10:45.66),3rd (3 pt),29th (CAP+17),35th (33:44.83),24th (10:42.43),26th (3:51.60),33rd (5:31.92),3rd (14:01.64),26th (3:47.65),25th (6:21.47)
29,31,ZEKE GROVE,440,24th (19:47.94),2nd (1:52.17),31T (1095 lb),28th (2:58:55.00),33T (CAP+3),9th (9 pt),15th (CAP+7),22nd (30:32.24),31st (11:35.56),22nd (3:46.47),30th (5:22.16),33T (16:07.00 ),34th (CAP+1),36th (CAP+1)
30,32,JOSH BRIDGES,434,14th (18:44.48),8th (2:11.30),39th (920 lb),29th (2:59:54.00),24th (10:33.86),37T (37 pt),22T (CAP+15),18th (29:07.90),28th (10:53.22),20th (3:41.82),9th (4:25.06),36th (16:28.00),33rd (CAP+1),29th (6:57.85)
31,33,MITCHEL STEVENSON,430,18th (19:21.95),31st (3:07.35),36th (1035 lb),27th (2:57:41.00),17th (9:56.91),33T (33 pt),34th (CAP+25),24th (30:37.61),12th (9:54.60),34th (4:07.82),15th (4:36.26),14th (14:34.71),15th (2:45.04),35th (7:57.39)
32,34,ETHAN HELBIG,410,17th (19:06.86),38th (4:26.08),30th (1105 lb),10th (2:48:13.00),33T (CAP+3),29th (29 pt),22T (CAP+15),38th (CAP),29th (11:11.22),37th (4:20.53),23rd (4:49.28),10th (14:22.61),17th (2:48.06),22nd (6:12.63)
33,35,ROYCE DUNNE,386,33rd (20:13.32),21st (2:48.08),1st (1255 lb),36th (3:13:18.00 ),37T (CAP+5),23rd (23 pt),37T (CAP+31),37th (35:19.05),34T (CAP+1),10th (3:31.05),28th (5:12.96),16th (14:44.18),32nd (CAP+1),33rd (7:47.84)
34,36,JARED ENDERTON,382,22nd (19:44.12),34th (3:28.04),5T (1230 lb),37th (3:18:57.00 ),31T (CAP+2),2nd (2 pt),16th (CAP+8),34th (33:41.27),34T (CAP+1),38th (4:27.95),37th (5:59.49),30th (15:50.59),29th (CAP+1),34th (7:49.07)
35,37,BRANDON LUCKETT,366,34th (20:48.03),39th (4:37.04),37th (1005 lb),21st (2:55:47.00),8th (9:27.47),26th (26 pt),33rd (CAP+24),16th (29:06.23),15th (10:12.50),35th (4:15.95),36th (5:57.63),20th (15:10.00),22nd (3:22.37),37th (CAP+3)
36,38,MARQUAN JONES,272,38th (21:53.27),33rd (3:18.70),34T (1040 lb),31st (3:01:58.00),31T (CAP+2),24th (24 pt),31st (CAP+19),33rd (33:33.78),30th (11:24.72),28th (3:52.99),29th (5:20.13),31st (15:53.33),13th (2:27.45),38th (CAP+35)
37,39,PABLO CHALFUN,210,39th (22:00.35),37th (3:59.01),20T (1150 lb),38th (3:22:54.00 ),37T (CAP+5),33T (33 pt),18T (CAP+10),36th (34:13.85),38th (CAP+3),32nd (4:05.15),38th (CAP+8),35th (16:07.85),31st (CAP+1),23rd (6:14.59)
38,--,ALEXANDRE CARON ROMAN KHRENNIKOV,182 0,5th (18:36.87),19th (2:46.49),10th (1205 lb),WD (--),WD (--),WD (--),WD (--),WD (--),WD (--),WD (--),WD (--),WD (--),WD (--),WD (--)
39,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [322]:
games_data_1[['crit_pos', 'crit_t']] = games_data_1.Crit.str.split(" ", expand=True,)
games_data_1[['muscle_up_pos', 'muscle_up_t']] = games_data_1.Muscle_Ups.str.split(" ", expand=True,)
games_data_1[['total_pos', 'total_t', 't1']] = games_data_1.Crossfit_Total.str.split(" ", expand=True,)
games_data_1[['row_pos', 'row_t', 't1']] = games_data_1.Marathon_Row.str.split(" ", expand=True,)
games_data_1[['battle_pos', 'battle_t']] = games_data_1.The_Battleground.str.split(" ", expand=True,)
games_data_1[['caj_pos', 'caj_t', 't1']] = games_data_1.Clean_and_Jerk_Ladder.str.split(" ", expand=True,)
games_data_1[['fib_pos', 'fib_t']] = games_data_1.Fibonacci.str.split(" ", expand=True,)
games_data_1[['tri_pos', 'tri_t']] = games_data_1.Triplus.str.split(" ", expand=True,)
games_data_1[['chaos_pos', 'chaos_t']] = games_data_1.Chaos.str.split(" ", expand=True,)
games_data_1[['bi1_pos', 'bi1_t']] = games_data_1.Bicouplet_1.str.split(" ", expand=True,)
games_data_1[['bi2_pos', 'bi2_t']] = games_data_1.Bicouplet_2.str.split(" ", expand=True,)
games_data_1[['twopull_pos', 'twopull_t', 't1']] = games_data_1.Two_Stroke_Pull.str.split(" ", expand=True,)
games_data_1[['hsw_pos', 'hsw_t']] = games_data_1.Handstand_walk.str.split(" ", expand=True,)
games_data_1[['aeneas_pos', 'aeneas_t']] = games_data_1.Aeneas.str.split(" ", expand=True,)




score_dat = games_data_1
cols_to_check = score_dat.columns
score_dat[cols_to_check] = score_dat[cols_to_check].replace({'\(':''}, regex=True)
score_dat[cols_to_check] = score_dat[cols_to_check].replace({'\)':''}, regex=True)
time_cols = ['crit_t', 'muscle_up_t', 'row_t', 'battle_t', 'fib_t', 'tri_t', 'chaos_t', 'bi1_t', 'bi2_t', 'twopull_t', 'hsw_t', 'aeneas_t']
score_dat[time_cols] = score_dat[time_cols].replace({'\.':''}, regex=True)
score_dat[time_cols] = score_dat[time_cols].replace({'\:':'.'}, regex=True)

In [324]:
score_dat

,RANK,NAME,POINTS,Crit,Muscle_Ups,Crossfit_Total,Marathon_Row,The_Battleground,Clean_and_Jerk_Ladder,Fibonacci,...,bi1_pos,bi1_t,bi2_pos,bi2_t,twopull_pos,twopull_t,hsw_pos,hsw_t,aeneas_pos,aeneas_t
0,2,MATHEW FRASER,1162,4th 18:36.55,3rd 2:00.16,8th 1215 lb,11th 2:48:36.00,2nd 8:49.40,7th 7 pt,1st 4:54.84,...,2nd,3.1036,4th,4.1077,4th,14.0603,3rd,1.4499,1st,3.5647
1,3,PATRICK VELLNER,942,35th 20:52.66,9th 2:12.69,2nd 1250 lb,5th 2:47:13.00,4th 8:54.79,11th 11 pt,4th 5:51.65,...,5th,3.1690,10th,4.3013,11th,14.2274,10th,2.2007,7th,4.5076
2,4,LUKAS H√ñGBERG,886,3rd 18:36.28,12th 2:22.36,11T 1190 lb,2nd 2:44:33.00,3rd 8:51.20,10th 10 pt,7T CAP+1,...,11th,3.3168,34th,5.3987,1st,13.3640,24th,3.3468,15th,5.2905
3,5,BRENT FIKOWSKI,886,9th 18:39.05,13th 2:28.15,20T 1150 lb,4th 2:47:03.00,7th 9:26.42,8th 8 pt,5T CAP,...,29th,3.5376,18th,4.3766,2nd,13.5560,27th,3.4976,4th,4.4217
4,6,BJ√ñRGVIN KARL GU√êMUNDSSON,834,6th 18:37.24,10th 2:16.87,15th 1185 lb,14th 2:51:17.00,6th 9:24.68,21st 21 pt,12th CAP+5,...,9th,3.2914,12th,4.3234,15th,14.3700,7th,2.1240,12th,5.1211
5,7,NOAH OHLSEN,786,30th 20:08.10,11th 2:21.67,11T 1190 lb,24th 2:57:12.00,10th 9:35.18,15th 15 pt,2nd 5:22.39,...,4th,3.1389,24th,4.5027,24th,15.1991,9th,2.1565,3rd,4.2526
6,8,COLE SAGER,760,13th 18:44.34,5th 2:01.85,17T 1165 lb,3rd 2:46:55.00,1st 8:35.01,33T 33 pt,22T CAP+15,...,25th,3.5108,32nd,5.2864,28th,15.4304,11th,2.2240,2nd,4.0711
7,9,RASMUS ANDERSEN,734,7T 18:37.38,16th 2:34.30,31T 1095 lb,7th 2:47:50.00,35T CAP+4,18th 18 pt,35T CAP+29,...,18th,3.4124,1st,4.0393,6th,14.1470,6th,2.0407,16th,5.3887
8,10,WILLY GEORGES,728,11th 18:43.29,15th 2:32.13,5T 1230 lb,20th 2:54:16.00,14th 9:48.52,16th 16 pt,22T CAP+15,...,1st,3.0367,2nd,4.0572,12th,14.3316,37T,CAP+2,32nd,7.3416
9,11,CODY ANDERSON,712,36th 20:53.50,4th 2:01.28,28T 1115 lb,33rd 3:03:40.00,16th 9:52.65,19th 19 pt,7T CAP+1,...,3rd,3.1141,7th,4.1751,38th,16.4984,1st,1.2942,13th,5.1783
10,12,SCOTT PANCHIK,694,37th 20:53.51,28th 2:58.57,4th 1235 lb,22nd 2:56:16.00,18th 10:02.80,4th 4 pt,13T CAP+6,...,6th,3.1783,5th,4.1149,32nd,15.5883,25th,3.4483,9th,4.5894
11,13,BEN SMITH,684,12th 18:44.23,18th 2:34.93,26th 1135 lb,13th 2:50:18.00,28th 10:56.46,5th 5 pt,32nd CAP+22,...,23rd,3.4788,3rd,4.0598,23rd,15.1665,4th,1.4973,8th,4.5428
12,14,ALEX ANDERSON,676,32nd 20:10.42,26th 2:56.18,11T 1190 lb,30th 3:00:43.00,13th 9:44.16,13th 13 pt,20th CAP+13,...,7th,3.2098,8th,4.1777,13th,14.3380,35th,CAP+1,10th,5.0109
13,15,DEAN LINDER-LEIGHTON,668,16th 18:57.11,14th 2:30.30,23T 1145 lb,16th 2:52:23.00,26th 10:44.10,25th 25 pt,5T CAP,...,16th,3.3940,11th,4.3212,22nd,15.1285,20th,3.0825,28th,6.4269
14,16,LOGAN COLLINS,652,29th 20:01.25,1st 1:46.00,17T 1165 lb,35th 3:05:48.00,20th 10:13.30,32nd 32 pt,3rd 5:48.06,...,8th,3.2761,19th,4.3829,37th,16.3153,5th,2.0316,6th,4.4937
15,17,ADRIAN MUNDWILER,652,1st 18:32.24,7th 2:10.78,23T 1145 lb,15th 2:51:27.00,12th 9:37.19,27th 27 pt,17th CAP+9,...,13th,3.3510,21st,4.4109,18th,15.0372,21st,3.1612,20th,6.0627
16,18,LUKAS ESSLINGER,648,23rd 19:45.71,22nd 2:48.44,3rd 1245 lb,1st 2:43:50.00,11th 9:36.00,22nd 22 pt,35T CAP+29,...,21st,3.4389,26th,4.5510,8th,14.2060,23rd,3.3228,14th,5.2031
17,19,JAMES NEWBURY,616,2nd 18:35.14,30th 3:06.24,38th 975 lb,8th 2:47:59.00,5th 9:11.87,30th 30 pt,30th CAP+18,...,17th,3.4037,35th,5.4316,17th,14.4980,14th,2.3821,30th,7.0390
18,20,SAXON PANCHIK,602,27th 19:57.50,17th 2:34.39,27th 1125 lb,34th 3:05:35.00,23rd 10:23.88,14th 14 pt,22T CAP+15,...,27th,3.5283,13th,4.3263,26th,15.3600,12th,2.2306,18th,5.4370
19,21,NICHOLAS URANKAR,590,15th 18:46.91,24th 2:52.47,5T 1230 lb,23rd 2:56:47.00,30th CAP+1,1st 1 pt,21st CAP+14,...,33rd,4.0612,14th,4.3546,29th,15.4500,19th,2.5675,11th,5.0511
20,22,FREDERICK AEGIDIUS,586,7T 18:37.38,23rd 2:49.22,19th 1155 lb,9th 2:48:08.00,15th 9:51.26,33T 33 pt,37T CAP+31,...,36th,4.1673,27th,5.0977,5th,14.1300,36th,CAP+1,5th,4.4732
21,23,SEAN SWEENEY,580,19th 19:41.96,20th 2:47.22,25th 1140 lb,25th 2:57:36.00,22nd 10:18.00,31st 31 pt,10T CAP+4,...,15th,3.3704,6th,4.1660,21st,15.1190,30th,CAP+1,21st,6.1105
22,24,ROGELIO GAMBOA,578,25th 19:48.78,25th 2:54.23,11T 1190 lb,6th 2:47:29.00,25th 10:35.18,6th 6 pt,28th CAP+16,...,12th,3.3459,16th,4.3672,27th,15.4180,16th,2.4691,27th,6.3890
23,25,KHAN PORTER,558,31st 20:08.13,36th 3:30.52,28T 1115 lb,19th 2:53:57.00,19th 10:08.39,28th 28 pt,13T CAP+6,...,24th,3.5070,17th,4.3756,9th,14.2213,37T,CAP+2,17th,5.4119
24,26,ALEC SMITH,548,28th 19:59.40,6th 2:07.87,33rd 1080 lb,18th 2:53:47.00,21st 10:14.38,12th 12 pt,18T CAP+10,...,14th,3.3686,22nd,4.4403,33T,16.0700,2nd,1.3860,26th,6.3342
25,27,ELLIOT SIMMONDS,530,21st 19:42.50,29th 2:59.49,34T 1040 lb,12th 2:49:13.00,9th 9:33.32,37T 37 pt,22T CAP+15,...,31st,4.0075,25th,4.5384,7th,14.1619,28th,3.5513,19th,5.5983
26,28,CRAIG KENNEY,516,10th 18:40.05,32nd 3:14.39,20T 1150 lb,17th 2:53:20.00,29th 10:56.80,17th 17 pt,10T CAP+4,...,30th,3.5533,20th,4.3886,25th,15.2100,18th,2.5289,24th,6.1744
27,29,JOHN COLTEY,486,26th 19:57.01,27th 2:56.70,9th 1210 lb,26th 2:57:39.00,35T CAP+4,20th 20 pt,9th CAP+2,...,19th,3.4172,31st,5.2498,19th,15.0677,8th,2.1551,31st,7.0645
28,30,TIM PAULSON,480,20th 19:42.00,35th 3:30.01,16th 1175 lb,32nd 3:02:09.00,27th 10:45.66,3rd 3 pt,29th CAP+17,...,26th,3.5160,33rd,5.3192,3rd,14.0164,26th,3.4765,25th,6.2147
29,31,ZEKE GROVE,440,24th 19:47.94,2nd 1:52.17,31T 1095 lb,28th 2:58:55.00,33T CAP+3,9th 9 pt,15th CAP+7,...,22nd,3.4647,30th,5.2216,33T,16.0700,34th,CAP+1,36th,CAP+1
30,32,JOSH BRIDGES,434,14th 18:44.48,8th 2:11.30,39th 920 lb,29th 2:59:54.00,24th 10:33.86,37T 37 pt,22T CAP+15,...,20th,3.4182,9th,4.2506,36th,16.2800,33rd,CAP+1,29th,6.5785
31,33,MITCHEL STEVENSON,430,18th 19:21.95,31st 3:07.35,36th 1035 lb,27th 2:57:41.00,17th 9:56.91,33T 33 pt,34th CAP+25,...,34th,4.0782,15th,4.3626,14th,14.3471,15th,2.4504,35th,7.5739
32,34,ETHAN HELBIG,410,17th 19:06.86,38th 4:26.08,30th 1105 lb,10th 2:48:13.00,33T CAP+3,29th 29 pt,22T CAP+15,...,37th,4.2053,23rd,4.4928,10th,14.2261,17th,2.4806,22nd,6.1263
33,35,ROYCE DUNNE,386,33rd 20:13.32,21st 2:48.08,1st 1255 lb,36th 3:13:18.00,37T CAP+5,23rd 23 pt,37T CAP+31,...,10th,3.3105,28th,5.1296,16th,14.4418,32nd,CAP+1,33rd,7.4784
34,36,JARED ENDERTON,382,22nd 19:44.12,34th 3:28.04,5T 1230 lb,37th 3:18:57.00,31T CAP+2,2nd 2 pt,16th CAP+8,...,38th,4.2795,37th,5.5949,30th,15.5059,29th,CAP+1,34th,7.4907
35,37,BRANDON LUCKETT,366,34th 20:48.03,39th 4:37.04,37th 1005 lb,21st 2:55:47.00,8th 9:27.47,26th 26 pt,33rd CAP+24,...,35th,4.1595,36th,5.5763,20th,15.1000,22nd,3.2237,37th,CAP+3
36,38,MARQUAN JONES,272,38th 21:53.27,33rd 3:18.70,34T 1040 lb,31st 3:01:58.00,31T CAP+2,24th 24 pt,31st CAP+19,...,28th,3.5299,29th,5.2013,31st,15.5333,13th,2.2745,38th,CAP+35
37,39,PABLO CHALFUN,210,39th 22:00.35,37th 3:59.01,20T 1150 lb,38th 3:22:54.00,37T CAP+5,33T 33 pt,18T CAP+10,...,32nd,4.0515,38th,CAP+8,35th,16.0785,31st,CAP+1,23rd,6.1459
38,--,ALEXANDRE CARON ROMAN KHRENNIKOV,182 0,5th 18:36.87,19th 2:46.49,10th 1205 lb,WD --,WD --,WD --,WD --,...,WD,--,WD,--,WD,--,WD,--,WD,--
39,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [325]:
score_dat.to_csv('/Users/thomasnicholson/Documents/games_data_m_2018.csv', index=False)